[tool.poetry]
name = "qs-display"
version = "0.1.0"
description = "Display Quadstick data on an Waveshare e-ink display"
authors = ["Felipe dos Santos <fss007@gmail.com>"]
readme = "README.md"
packages = [{include = "quadstick_display"}]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.3"
werkzeug = "^3.0.3"
pillow = "^10.4.0"

# Raspberry Pi dependencies
spidev = {version = "^3.6", platform = "linux"}
gpiozero = {version = "^2.0.1", platform = "linux"}
rpi-gpio = {version = "^0.7.1", platform = "linux"}
lgpio = {version = "^0.2.2.0", markers = "sys_platform == 'linux' and (platform_machine == 'aarch64' or platform_machine == 'armv7l')"}

# Waveshare e-Paper display dependencies
jetson-gpio = {version = "^2.1.6", platform = "linux"}
waveshare-epd = { git = "https://github.com/waveshareteam/e-Paper.git", branch = "master", subdirectory = "RaspberryPi_JetsonNano/python" }


[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
ruff = "^0.16.1"

[tool.ruff]
target-version = "py310"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
