# Custom app to Display Quadstick key settings on an e-ink display
# 2024 felipe.dos.santos

name: "Verify Quadstick Display"

on:
  pull_request:
  push:
    tags-ignore:
      - 'v*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: ./.github/workflows/_verify.yml
